"""Generate NINA Advanced Sequencer XML files from PhotonScript projects."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from xml.dom import minidom
from typing import Optional

from photonscript.shared.models import (
    NinaSequenceFile, NinaSequenceTarget, ExposurePlan, FilterType,
)


# NINA filter wheel position mapping (customize per setup)
FILTER_POSITIONS: dict[FilterType, int] = {
    FilterType.LUMINANCE: 0,
    FilterType.RED: 1,
    FilterType.GREEN: 2,
    FilterType.BLUE: 3,
    FilterType.HA: 4,
    FilterType.OIII: 5,
    FilterType.SII: 6,
}


def _hours_to_hms(hours: float) -> str:
    """Convert decimal hours to HH:MM:SS string."""
    h = int(hours)
    m = int((hours - h) * 60)
    s = int(((hours - h) * 60 - m) * 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def _deg_to_dms(degrees: float) -> str:
    """Convert decimal degrees to ±DD:MM:SS string."""
    sign = "+" if degrees >= 0 else "-"
    d = abs(degrees)
    dd = int(d)
    mm = int((d - dd) * 60)
    ss = int(((d - dd) * 60 - mm) * 60)
    return f"{sign}{dd:02d}:{mm:02d}:{ss:02d}"


def generate_nina_xml(sequence: NinaSequenceFile) -> str:
    """Generate a NINA Advanced Sequencer compatible XML file.

    NINA uses a complex XML schema for its advanced sequencer.  This generates
    a simplified but valid sequence that NINA can import.
    """
    root = ET.Element("AdvancedSequence")
    root.set("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")

    # Sequence metadata
    meta = ET.SubElement(root, "SequenceMetaData")
    ET.SubElement(meta, "Name").text = sequence.name
    ET.SubElement(meta, "Description").text = f"Generated by PhotonScript"

    # Start area — safety checks
    start = ET.SubElement(root, "StartArea")
    if sequence.targets and sequence.targets[0].cool_camera:
        cool = ET.SubElement(start, "CoolCamera")
        ET.SubElement(cool, "Temperature").text = str(sequence.targets[0].camera_temp_c)
        ET.SubElement(cool, "Duration").text = "600"  # 10 min cooldown

    # Target area — main imaging loop
    target_area = ET.SubElement(root, "TargetArea")

    for seq_target in sequence.targets:
        target_block = ET.SubElement(target_area, "DeepSkyObjectContainer")

        # Target coordinates
        target_elem = ET.SubElement(target_block, "Target")
        ET.SubElement(target_elem, "Name").text = seq_target.name
        coords = ET.SubElement(target_elem, "Coordinates")
        ET.SubElement(coords, "RA").text = _hours_to_hms(seq_target.ra_hours)
        ET.SubElement(coords, "Dec").text = _deg_to_dms(seq_target.dec_degrees)
        ET.SubElement(target_elem, "Rotation").text = str(seq_target.rotation)

        # Conditions
        conditions = ET.SubElement(target_block, "Conditions")
        alt_cond = ET.SubElement(conditions, "AltitudeCondition")
        ET.SubElement(alt_cond, "MinimumAltitude").text = str(sequence.wait_for_altitude)

        # Triggers
        triggers = ET.SubElement(target_block, "Triggers")
        if seq_target.meridian_flip:
            ET.SubElement(triggers, "MeridianFlipTrigger")
        if seq_target.auto_focus_interval_minutes > 0:
            af = ET.SubElement(triggers, "AutofocusTrigger")
            ET.SubElement(af, "IntervalMinutes").text = str(seq_target.auto_focus_interval_minutes)
        if seq_target.dither_every_n > 0:
            dither = ET.SubElement(triggers, "DitherTrigger")
            ET.SubElement(dither, "EveryNFrames").text = str(seq_target.dither_every_n)

        # Instructions — sequential container
        instructions = ET.SubElement(target_block, "Instructions")

        # Slew & Center
        if seq_target.slew_and_center:
            slew = ET.SubElement(instructions, "SlewAndCenter")
            ET.SubElement(slew, "Coordinates").text = f"{_hours_to_hms(seq_target.ra_hours)} {_deg_to_dms(seq_target.dec_degrees)}"

        # Start guiding
        if seq_target.start_guiding:
            ET.SubElement(instructions, "StartGuiding")

        # Autofocus on start
        if seq_target.auto_focus_on_start:
            ET.SubElement(instructions, "RunAutofocus")

        # Exposure sets
        for exp in seq_target.exposures:
            remaining = exp.count - exp.acquired
            if remaining <= 0:
                continue

            exp_set = ET.SubElement(instructions, "TakeExposures")
            ET.SubElement(exp_set, "ExposureTime").text = str(exp.exposure_seconds)
            ET.SubElement(exp_set, "FilterName").text = exp.filter_type.value
            ET.SubElement(exp_set, "FilterPosition").text = str(
                FILTER_POSITIONS.get(exp.filter_type, 0)
            )
            ET.SubElement(exp_set, "TotalExposures").text = str(remaining)
            ET.SubElement(exp_set, "Gain").text = str(exp.gain)
            ET.SubElement(exp_set, "Offset").text = str(exp.offset)
            ET.SubElement(exp_set, "Binning").text = f"{exp.binning}x{exp.binning}"

    # End area — park & warm
    end = ET.SubElement(root, "EndArea")
    if sequence.warm_camera_on_finish:
        ET.SubElement(end, "WarmCamera")
    if sequence.park_on_finish:
        ET.SubElement(end, "ParkScope")

    # Pretty-print
    rough = ET.tostring(root, encoding="unicode")
    dom = minidom.parseString(rough)
    return dom.toprettyxml(indent="  ", encoding=None)


def build_sequence_for_night(
    name: str,
    targets: list[NinaSequenceTarget],
    min_altitude: float = 30.0,
) -> NinaSequenceFile:
    """Build a NinaSequenceFile from a list of targets for tonight."""
    return NinaSequenceFile(
        name=name,
        targets=targets,
        wait_for_altitude=min_altitude,
        park_on_finish=True,
        warm_camera_on_finish=True,
    )
